# Generated by Django 2.0.6 on 2018-06-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drg', models.CharField(max_length=1024)),
                ('total_discharges', models.IntegerField(db_index=True, default=0)),
                ('avg_covered_charges', models.IntegerField(db_index=True)),
                ('avg_total_payments', models.IntegerField(db_index=True)),
                ('avg_medicare_payments', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('street_address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(db_index=True, max_length=3)),
                ('zip_code', models.CharField(max_length=10)),
                ('region_description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='inpatient',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthset.Provider'),
        ),
    ]
