# Generated by Django 2.0.6 on 2018-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='avg_covered_charges',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='avg_medicare_payments',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='avg_total_payments',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='total_discharges',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
