# Generated by Django 2.0.6 on 2018-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthset', '0002_auto_20180612_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='total_discharges',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
